// Code generated by protoc-gen-go. DO NOT EDIT.
// source: greetpb/greet.proto

package greetpb

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Greeting struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Greeting) Reset()         { *m = Greeting{} }
func (m *Greeting) String() string { return proto.CompactTextString(m) }
func (*Greeting) ProtoMessage()    {}
func (*Greeting) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd67c47c0cf51822, []int{0}
}

func (m *Greeting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Greeting.Unmarshal(m, b)
}
func (m *Greeting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Greeting.Marshal(b, m, deterministic)
}
func (m *Greeting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Greeting.Merge(m, src)
}
func (m *Greeting) XXX_Size() int {
	return xxx_messageInfo_Greeting.Size(m)
}
func (m *Greeting) XXX_DiscardUnknown() {
	xxx_messageInfo_Greeting.DiscardUnknown(m)
}

var xxx_messageInfo_Greeting proto.InternalMessageInfo

func (m *Greeting) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Greeting) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

type Summating struct {
	Num1                 int64    `protobuf:"varint,1,opt,name=num1,proto3" json:"num1,omitempty"`
	Num2                 int64    `protobuf:"varint,2,opt,name=num2,proto3" json:"num2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Summating) Reset()         { *m = Summating{} }
func (m *Summating) String() string { return proto.CompactTextString(m) }
func (*Summating) ProtoMessage()    {}
func (*Summating) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd67c47c0cf51822, []int{1}
}

func (m *Summating) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Summating.Unmarshal(m, b)
}
func (m *Summating) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Summating.Marshal(b, m, deterministic)
}
func (m *Summating) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Summating.Merge(m, src)
}
func (m *Summating) XXX_Size() int {
	return xxx_messageInfo_Summating.Size(m)
}
func (m *Summating) XXX_DiscardUnknown() {
	xxx_messageInfo_Summating.DiscardUnknown(m)
}

var xxx_messageInfo_Summating proto.InternalMessageInfo

func (m *Summating) GetNum1() int64 {
	if m != nil {
		return m.Num1
	}
	return 0
}

func (m *Summating) GetNum2() int64 {
	if m != nil {
		return m.Num2
	}
	return 0
}

type SummationRequest struct {
	Summation            *Summating `protobuf:"bytes,1,opt,name=summation,proto3" json:"summation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SummationRequest) Reset()         { *m = SummationRequest{} }
func (m *SummationRequest) String() string { return proto.CompactTextString(m) }
func (*SummationRequest) ProtoMessage()    {}
func (*SummationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd67c47c0cf51822, []int{2}
}

func (m *SummationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SummationRequest.Unmarshal(m, b)
}
func (m *SummationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SummationRequest.Marshal(b, m, deterministic)
}
func (m *SummationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SummationRequest.Merge(m, src)
}
func (m *SummationRequest) XXX_Size() int {
	return xxx_messageInfo_SummationRequest.Size(m)
}
func (m *SummationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SummationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SummationRequest proto.InternalMessageInfo

func (m *SummationRequest) GetSummation() *Summating {
	if m != nil {
		return m.Summation
	}
	return nil
}

type SummationResponse struct {
	Result               int64    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SummationResponse) Reset()         { *m = SummationResponse{} }
func (m *SummationResponse) String() string { return proto.CompactTextString(m) }
func (*SummationResponse) ProtoMessage()    {}
func (*SummationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd67c47c0cf51822, []int{3}
}

func (m *SummationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SummationResponse.Unmarshal(m, b)
}
func (m *SummationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SummationResponse.Marshal(b, m, deterministic)
}
func (m *SummationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SummationResponse.Merge(m, src)
}
func (m *SummationResponse) XXX_Size() int {
	return xxx_messageInfo_SummationResponse.Size(m)
}
func (m *SummationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SummationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SummationResponse proto.InternalMessageInfo

func (m *SummationResponse) GetResult() int64 {
	if m != nil {
		return m.Result
	}
	return 0
}

type GreetRequest struct {
	Greeting             *Greeting `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GreetRequest) Reset()         { *m = GreetRequest{} }
func (m *GreetRequest) String() string { return proto.CompactTextString(m) }
func (*GreetRequest) ProtoMessage()    {}
func (*GreetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd67c47c0cf51822, []int{4}
}

func (m *GreetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetRequest.Unmarshal(m, b)
}
func (m *GreetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetRequest.Marshal(b, m, deterministic)
}
func (m *GreetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetRequest.Merge(m, src)
}
func (m *GreetRequest) XXX_Size() int {
	return xxx_messageInfo_GreetRequest.Size(m)
}
func (m *GreetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GreetRequest proto.InternalMessageInfo

func (m *GreetRequest) GetGreeting() *Greeting {
	if m != nil {
		return m.Greeting
	}
	return nil
}

type GreetResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetResponse) Reset()         { *m = GreetResponse{} }
func (m *GreetResponse) String() string { return proto.CompactTextString(m) }
func (*GreetResponse) ProtoMessage()    {}
func (*GreetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd67c47c0cf51822, []int{5}
}

func (m *GreetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetResponse.Unmarshal(m, b)
}
func (m *GreetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetResponse.Marshal(b, m, deterministic)
}
func (m *GreetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetResponse.Merge(m, src)
}
func (m *GreetResponse) XXX_Size() int {
	return xxx_messageInfo_GreetResponse.Size(m)
}
func (m *GreetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GreetResponse proto.InternalMessageInfo

func (m *GreetResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type GreetManyTimesRequest struct {
	Greeting             *Greeting `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GreetManyTimesRequest) Reset()         { *m = GreetManyTimesRequest{} }
func (m *GreetManyTimesRequest) String() string { return proto.CompactTextString(m) }
func (*GreetManyTimesRequest) ProtoMessage()    {}
func (*GreetManyTimesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd67c47c0cf51822, []int{6}
}

func (m *GreetManyTimesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetManyTimesRequest.Unmarshal(m, b)
}
func (m *GreetManyTimesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetManyTimesRequest.Marshal(b, m, deterministic)
}
func (m *GreetManyTimesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetManyTimesRequest.Merge(m, src)
}
func (m *GreetManyTimesRequest) XXX_Size() int {
	return xxx_messageInfo_GreetManyTimesRequest.Size(m)
}
func (m *GreetManyTimesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetManyTimesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GreetManyTimesRequest proto.InternalMessageInfo

func (m *GreetManyTimesRequest) GetGreeting() *Greeting {
	if m != nil {
		return m.Greeting
	}
	return nil
}

type GreetManyTimesResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetManyTimesResponse) Reset()         { *m = GreetManyTimesResponse{} }
func (m *GreetManyTimesResponse) String() string { return proto.CompactTextString(m) }
func (*GreetManyTimesResponse) ProtoMessage()    {}
func (*GreetManyTimesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd67c47c0cf51822, []int{7}
}

func (m *GreetManyTimesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetManyTimesResponse.Unmarshal(m, b)
}
func (m *GreetManyTimesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetManyTimesResponse.Marshal(b, m, deterministic)
}
func (m *GreetManyTimesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetManyTimesResponse.Merge(m, src)
}
func (m *GreetManyTimesResponse) XXX_Size() int {
	return xxx_messageInfo_GreetManyTimesResponse.Size(m)
}
func (m *GreetManyTimesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetManyTimesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GreetManyTimesResponse proto.InternalMessageInfo

func (m *GreetManyTimesResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type GreetLongResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetLongResponse) Reset()         { *m = GreetLongResponse{} }
func (m *GreetLongResponse) String() string { return proto.CompactTextString(m) }
func (*GreetLongResponse) ProtoMessage()    {}
func (*GreetLongResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd67c47c0cf51822, []int{8}
}

func (m *GreetLongResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetLongResponse.Unmarshal(m, b)
}
func (m *GreetLongResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetLongResponse.Marshal(b, m, deterministic)
}
func (m *GreetLongResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetLongResponse.Merge(m, src)
}
func (m *GreetLongResponse) XXX_Size() int {
	return xxx_messageInfo_GreetLongResponse.Size(m)
}
func (m *GreetLongResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetLongResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GreetLongResponse proto.InternalMessageInfo

func (m *GreetLongResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*Greeting)(nil), "greet.Greeting")
	proto.RegisterType((*Summating)(nil), "greet.Summating")
	proto.RegisterType((*SummationRequest)(nil), "greet.SummationRequest")
	proto.RegisterType((*SummationResponse)(nil), "greet.SummationResponse")
	proto.RegisterType((*GreetRequest)(nil), "greet.GreetRequest")
	proto.RegisterType((*GreetResponse)(nil), "greet.GreetResponse")
	proto.RegisterType((*GreetManyTimesRequest)(nil), "greet.GreetManyTimesRequest")
	proto.RegisterType((*GreetManyTimesResponse)(nil), "greet.GreetManyTimesResponse")
	proto.RegisterType((*GreetLongResponse)(nil), "greet.GreetLongResponse")
}

func init() { proto.RegisterFile("greetpb/greet.proto", fileDescriptor_cd67c47c0cf51822) }

var fileDescriptor_cd67c47c0cf51822 = []byte{
	// 362 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x5f, 0x4f, 0xfa, 0x30,
	0x14, 0x65, 0x3f, 0x7e, 0x20, 0xbd, 0xfe, 0x83, 0xa2, 0x48, 0x50, 0x12, 0xd3, 0x17, 0x49, 0x48,
	0x10, 0x87, 0x4f, 0x9a, 0xf8, 0x40, 0x8c, 0xbe, 0x28, 0x89, 0xc3, 0x27, 0x5f, 0xcc, 0x30, 0x75,
	0x59, 0x42, 0x3b, 0x5c, 0x37, 0x13, 0x3f, 0xa9, 0x5f, 0xc7, 0xec, 0xd2, 0xce, 0x82, 0x7f, 0x48,
	0x7c, 0x5a, 0x7b, 0xee, 0xb9, 0xe7, 0xdc, 0x7b, 0x96, 0x42, 0x3d, 0x88, 0x39, 0x4f, 0x66, 0x93,
	0x63, 0xfc, 0xf6, 0x66, 0x71, 0x94, 0x44, 0xb4, 0x84, 0x17, 0x76, 0x05, 0x95, 0xeb, 0xec, 0x10,
	0xca, 0x80, 0xb6, 0x01, 0x9e, 0xc3, 0x58, 0x25, 0x8f, 0xd2, 0x17, 0xbc, 0xe9, 0x1c, 0x3a, 0x1d,
	0xe2, 0x11, 0x44, 0x46, 0xbe, 0xe0, 0x74, 0x1f, 0xc8, 0xd4, 0x37, 0xd5, 0x7f, 0x58, 0xad, 0x64,
	0x40, 0x56, 0x64, 0x03, 0x20, 0xe3, 0x54, 0x08, 0x1f, 0x85, 0x28, 0xfc, 0x97, 0xa9, 0x38, 0x41,
	0x89, 0xa2, 0x87, 0x67, 0x8d, 0xb9, 0xd8, 0x38, 0xc7, 0x5c, 0x36, 0x84, 0xaa, 0x6e, 0x8a, 0xa4,
	0xc7, 0x5f, 0x52, 0xae, 0x12, 0xda, 0x03, 0xa2, 0x0c, 0x86, 0x02, 0xeb, 0x6e, 0xb5, 0x37, 0x1f,
	0x3c, 0x37, 0xf0, 0x3e, 0x29, 0xac, 0x0b, 0x35, 0x4b, 0x43, 0xcd, 0x22, 0xa9, 0x38, 0x6d, 0x40,
	0x39, 0xe6, 0x2a, 0x9d, 0x26, 0x7a, 0x04, 0x7d, 0x63, 0xe7, 0xb0, 0x81, 0xdb, 0x1a, 0xb3, 0x2e,
	0x54, 0x02, 0xbd, 0xbd, 0xf6, 0xda, 0xd6, 0x5e, 0x26, 0x14, 0x2f, 0x27, 0xb0, 0x23, 0xd8, 0xd4,
	0xcd, 0xdf, 0xba, 0x90, 0xdc, 0xe5, 0x12, 0x76, 0x91, 0x78, 0xeb, 0xcb, 0xb7, 0xfb, 0x50, 0x70,
	0xf5, 0x27, 0xbb, 0x3e, 0x34, 0x96, 0x55, 0x56, 0xf8, 0x76, 0xa1, 0x86, 0x1d, 0x37, 0x91, 0x0c,
	0x56, 0x91, 0xdd, 0x91, 0x95, 0xfd, 0x98, 0xc7, 0xaf, 0xe1, 0x13, 0xa7, 0x67, 0x50, 0x1c, 0xa7,
	0x82, 0xee, 0x2d, 0xe6, 0x9d, 0xff, 0x9b, 0x56, 0xf3, 0x6b, 0x61, 0xee, 0xc2, 0x0a, 0xee, 0xbb,
	0xa3, 0xb3, 0x35, 0x62, 0xa7, 0x50, 0xc2, 0x3b, 0xad, 0xdb, 0x3b, 0x1a, 0xa9, 0x9d, 0x45, 0xd0,
	0xc8, 0xd0, 0x3b, 0xd8, 0x5a, 0xdc, 0x9a, 0x1e, 0xd8, 0xcc, 0xe5, 0x48, 0x5b, 0xed, 0x1f, 0xaa,
	0x46, 0xb0, 0xef, 0xd0, 0x0b, 0x20, 0x59, 0x22, 0xbf, 0x0c, 0xd3, 0xb4, 0x41, 0x3b, 0x3d, 0x56,
	0xe8, 0x38, 0x43, 0xf2, 0xb0, 0xa6, 0x1f, 0xd0, 0xa4, 0x8c, 0x6f, 0x67, 0xf0, 0x11, 0x00, 0x00,
	0xff, 0xff, 0x80, 0xe6, 0x47, 0x9f, 0x52, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SummationServiceClient is the client API for SummationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SummationServiceClient interface {
	Sum(ctx context.Context, in *SummationRequest, opts ...grpc.CallOption) (*SummationResponse, error)
}

type summationServiceClient struct {
	cc *grpc.ClientConn
}

func NewSummationServiceClient(cc *grpc.ClientConn) SummationServiceClient {
	return &summationServiceClient{cc}
}

func (c *summationServiceClient) Sum(ctx context.Context, in *SummationRequest, opts ...grpc.CallOption) (*SummationResponse, error) {
	out := new(SummationResponse)
	err := c.cc.Invoke(ctx, "/greet.SummationService/Sum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SummationServiceServer is the server API for SummationService service.
type SummationServiceServer interface {
	Sum(context.Context, *SummationRequest) (*SummationResponse, error)
}

// UnimplementedSummationServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSummationServiceServer struct {
}

func (*UnimplementedSummationServiceServer) Sum(ctx context.Context, req *SummationRequest) (*SummationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sum not implemented")
}

func RegisterSummationServiceServer(s *grpc.Server, srv SummationServiceServer) {
	s.RegisterService(&_SummationService_serviceDesc, srv)
}

func _SummationService_Sum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SummationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SummationServiceServer).Sum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greet.SummationService/Sum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SummationServiceServer).Sum(ctx, req.(*SummationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SummationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "greet.SummationService",
	HandlerType: (*SummationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sum",
			Handler:    _SummationService_Sum_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "greetpb/greet.proto",
}

// GreetServiceClient is the client API for GreetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreetServiceClient interface {
	//unary api
	Greet(ctx context.Context, in *GreetRequest, opts ...grpc.CallOption) (*GreetResponse, error)
	//stream api
	GreetManyTimes(ctx context.Context, in *GreetManyTimesRequest, opts ...grpc.CallOption) (GreetService_GreetManyTimesClient, error)
	//client stream
	LongGreet(ctx context.Context, opts ...grpc.CallOption) (GreetService_LongGreetClient, error)
}

type greetServiceClient struct {
	cc *grpc.ClientConn
}

func NewGreetServiceClient(cc *grpc.ClientConn) GreetServiceClient {
	return &greetServiceClient{cc}
}

func (c *greetServiceClient) Greet(ctx context.Context, in *GreetRequest, opts ...grpc.CallOption) (*GreetResponse, error) {
	out := new(GreetResponse)
	err := c.cc.Invoke(ctx, "/greet.GreetService/Greet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greetServiceClient) GreetManyTimes(ctx context.Context, in *GreetManyTimesRequest, opts ...grpc.CallOption) (GreetService_GreetManyTimesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GreetService_serviceDesc.Streams[0], "/greet.GreetService/GreetManyTimes", opts...)
	if err != nil {
		return nil, err
	}
	x := &greetServiceGreetManyTimesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GreetService_GreetManyTimesClient interface {
	Recv() (*GreetManyTimesResponse, error)
	grpc.ClientStream
}

type greetServiceGreetManyTimesClient struct {
	grpc.ClientStream
}

func (x *greetServiceGreetManyTimesClient) Recv() (*GreetManyTimesResponse, error) {
	m := new(GreetManyTimesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greetServiceClient) LongGreet(ctx context.Context, opts ...grpc.CallOption) (GreetService_LongGreetClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GreetService_serviceDesc.Streams[1], "/greet.GreetService/LongGreet", opts...)
	if err != nil {
		return nil, err
	}
	x := &greetServiceLongGreetClient{stream}
	return x, nil
}

type GreetService_LongGreetClient interface {
	Send(*GreetRequest) error
	CloseAndRecv() (*GreetLongResponse, error)
	grpc.ClientStream
}

type greetServiceLongGreetClient struct {
	grpc.ClientStream
}

func (x *greetServiceLongGreetClient) Send(m *GreetRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greetServiceLongGreetClient) CloseAndRecv() (*GreetLongResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(GreetLongResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GreetServiceServer is the server API for GreetService service.
type GreetServiceServer interface {
	//unary api
	Greet(context.Context, *GreetRequest) (*GreetResponse, error)
	//stream api
	GreetManyTimes(*GreetManyTimesRequest, GreetService_GreetManyTimesServer) error
	//client stream
	LongGreet(GreetService_LongGreetServer) error
}

// UnimplementedGreetServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGreetServiceServer struct {
}

func (*UnimplementedGreetServiceServer) Greet(ctx context.Context, req *GreetRequest) (*GreetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Greet not implemented")
}
func (*UnimplementedGreetServiceServer) GreetManyTimes(req *GreetManyTimesRequest, srv GreetService_GreetManyTimesServer) error {
	return status.Errorf(codes.Unimplemented, "method GreetManyTimes not implemented")
}
func (*UnimplementedGreetServiceServer) LongGreet(srv GreetService_LongGreetServer) error {
	return status.Errorf(codes.Unimplemented, "method LongGreet not implemented")
}

func RegisterGreetServiceServer(s *grpc.Server, srv GreetServiceServer) {
	s.RegisterService(&_GreetService_serviceDesc, srv)
}

func _GreetService_Greet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GreetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreetServiceServer).Greet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greet.GreetService/Greet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreetServiceServer).Greet(ctx, req.(*GreetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GreetService_GreetManyTimes_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GreetManyTimesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreetServiceServer).GreetManyTimes(m, &greetServiceGreetManyTimesServer{stream})
}

type GreetService_GreetManyTimesServer interface {
	Send(*GreetManyTimesResponse) error
	grpc.ServerStream
}

type greetServiceGreetManyTimesServer struct {
	grpc.ServerStream
}

func (x *greetServiceGreetManyTimesServer) Send(m *GreetManyTimesResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _GreetService_LongGreet_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreetServiceServer).LongGreet(&greetServiceLongGreetServer{stream})
}

type GreetService_LongGreetServer interface {
	SendAndClose(*GreetLongResponse) error
	Recv() (*GreetRequest, error)
	grpc.ServerStream
}

type greetServiceLongGreetServer struct {
	grpc.ServerStream
}

func (x *greetServiceLongGreetServer) SendAndClose(m *GreetLongResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greetServiceLongGreetServer) Recv() (*GreetRequest, error) {
	m := new(GreetRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _GreetService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "greet.GreetService",
	HandlerType: (*GreetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Greet",
			Handler:    _GreetService_Greet_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GreetManyTimes",
			Handler:       _GreetService_GreetManyTimes_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "LongGreet",
			Handler:       _GreetService_LongGreet_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "greetpb/greet.proto",
}
