# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    docker login -u $(dockerId) -p $(pswd)
    /bin/bash build.sh "docker/frontend" "uid09552/goexamplefrontend" $(build.buildId)
    rm -fr /home/vsts/.docker/config.json
  displayName: 'docker build frontend'
  
- script: |
    docker login -u $(dockerId) -p $(pswd)
    /bin/bash build.sh "docker/main" "uid09552/goexamplemain" $(build.buildId)
    rm -fr /home/vsts/.docker/config.json
  displayName: 'docker build main'

- script: |
    docker login -u $(dockerId) -p $(pswd)
    /bin/bash build.sh "docker/backend" "uid09552/goexamplebackend" $(build.buildId)
    rm -fr /home/vsts/.docker/config.json
  displayName: 'docker build backend'

- script: |
    docker login -u $(dockerId) -p $(pswd)
    /bin/bash build.sh "docker/reposervice" "uid09552/goexamplerepo" $(build.buildId)
    rm -fr /home/vsts/.docker/config.json
  displayName: 'docker build reposervice'