# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  IMAGE: 'uid09552/goexamplefrontend'

steps:
- script: |
    cd docker/frontend
    ID=$(docker build  -t ${IMAGE}  .  | tail -1 | sed 's/.*Successfully built \(.*\)$/\1/')
    docker tag $(ID) uid09552/goexamplefrontend:latest
    docker tag $(ID) uid09552/goexamplefrontend:$(build.buildId)
    docker login -u $(dockerId) -p $(pswd)
    docker push $(IMAGE):$(build.buildId)
    docker push uid09552/goexamplefrontend:latest
  displayName: 'docker build frontend'
