kind: Pod
apiVersion: v1
metadata:
  name: goexamplefrontend
  labels:
    name: goexamplefrontend
spec:
  containers:
  - name: goexamplefrontend
    image: uid09552/goexamplefrontend:latest
    ports:
      - containerPort: 8080
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 3
      periodSeconds: 3 
  - name: goexamplebackend
    image: uid09552/goexamplebackend:latest
    ports:
      - containerPort: 8081