apiVersion: v1
kind: Service
metadata:
  labels:
    app: goexamplemain
  name: goexamplemain
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 32000
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: goexamplemain
  sessionAffinity: None
  type: NodePort
