apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.AppName }}
  labels:
    app: {{ .Values.AppName }}
spec:
  replicas: 2
  minReadySeconds: 5
  strategy:
  # indicate which strategy we want for rolling update
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: {{ .Values.AppName }}
  template:
    metadata:
      labels:
        app: {{ .Values.AppName }}
    spec:
      containers:
      - name: {{ .Values.AppName }}frontend
        image: uid09552/goexamplefrontend:latest
        ports:
        - containerPort: 8080
        env:
        - name: name
          valueFrom:
            configMapKeyRef:
              name: test-configmap
              key: name
      - name: {{ .Values.AppName }}backend
        image: uid09552/goexamplebackend:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8081
