apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: {{ .Values.AppName }}main
  name: {{ .Values.AppName }}main
spec:
  minReadySeconds: 5
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ .Values.AppName }}main
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.AppName }}main
        sha: {{ .Values.BUILD_SOURCE_VERSION }}
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 2000
      containers:
      - env:
        - name: VERSION
          value: v1.5.hf
        - name: GO_EXAMPLE_SERVICE
          valueFrom:
            configMapKeyRef:
              key: GO_EXAMPLE_SERVICE
              name: helmconfigmapmain-cfg
              optional: false
        image: uid09552/goexamplemain:latest
        imagePullPolicy: Always
        name: {{ .Values.AppName }}main
        securityContext: 
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 8080
          name: 8080tcp00
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
