apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.AppName }}main
  name: {{ .Values.AppName }}main
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 33000
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ .Values.AppName }}main
  sessionAffinity: None
  type: NodePort
