// Code generated by protoc-gen-go. DO NOT EDIT.
// source: blog.proto

package blogpg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_blog_89641c5255cf15cd, []int{0}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Blog struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthorId             string   `protobuf:"bytes,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Blog) Reset()         { *m = Blog{} }
func (m *Blog) String() string { return proto.CompactTextString(m) }
func (*Blog) ProtoMessage()    {}
func (*Blog) Descriptor() ([]byte, []int) {
	return fileDescriptor_blog_89641c5255cf15cd, []int{1}
}
func (m *Blog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blog.Unmarshal(m, b)
}
func (m *Blog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blog.Marshal(b, m, deterministic)
}
func (dst *Blog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blog.Merge(dst, src)
}
func (m *Blog) XXX_Size() int {
	return xxx_messageInfo_Blog.Size(m)
}
func (m *Blog) XXX_DiscardUnknown() {
	xxx_messageInfo_Blog.DiscardUnknown(m)
}

var xxx_messageInfo_Blog proto.InternalMessageInfo

func (m *Blog) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Blog) GetAuthorId() string {
	if m != nil {
		return m.AuthorId
	}
	return ""
}

func (m *Blog) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Blog) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type CreateBlogReq struct {
	Blog                 *Blog    `protobuf:"bytes,1,opt,name=blog,proto3" json:"blog,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBlogReq) Reset()         { *m = CreateBlogReq{} }
func (m *CreateBlogReq) String() string { return proto.CompactTextString(m) }
func (*CreateBlogReq) ProtoMessage()    {}
func (*CreateBlogReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_blog_89641c5255cf15cd, []int{2}
}
func (m *CreateBlogReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBlogReq.Unmarshal(m, b)
}
func (m *CreateBlogReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBlogReq.Marshal(b, m, deterministic)
}
func (dst *CreateBlogReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBlogReq.Merge(dst, src)
}
func (m *CreateBlogReq) XXX_Size() int {
	return xxx_messageInfo_CreateBlogReq.Size(m)
}
func (m *CreateBlogReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBlogReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBlogReq proto.InternalMessageInfo

func (m *CreateBlogReq) GetBlog() *Blog {
	if m != nil {
		return m.Blog
	}
	return nil
}

type CreateBlogRes struct {
	Blog                 *Blog    `protobuf:"bytes,1,opt,name=blog,proto3" json:"blog,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBlogRes) Reset()         { *m = CreateBlogRes{} }
func (m *CreateBlogRes) String() string { return proto.CompactTextString(m) }
func (*CreateBlogRes) ProtoMessage()    {}
func (*CreateBlogRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_blog_89641c5255cf15cd, []int{3}
}
func (m *CreateBlogRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBlogRes.Unmarshal(m, b)
}
func (m *CreateBlogRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBlogRes.Marshal(b, m, deterministic)
}
func (dst *CreateBlogRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBlogRes.Merge(dst, src)
}
func (m *CreateBlogRes) XXX_Size() int {
	return xxx_messageInfo_CreateBlogRes.Size(m)
}
func (m *CreateBlogRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBlogRes.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBlogRes proto.InternalMessageInfo

func (m *CreateBlogRes) GetBlog() *Blog {
	if m != nil {
		return m.Blog
	}
	return nil
}

type UpdateBlogReq struct {
	Blog                 *Blog    `protobuf:"bytes,1,opt,name=blog,proto3" json:"blog,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateBlogReq) Reset()         { *m = UpdateBlogReq{} }
func (m *UpdateBlogReq) String() string { return proto.CompactTextString(m) }
func (*UpdateBlogReq) ProtoMessage()    {}
func (*UpdateBlogReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_blog_89641c5255cf15cd, []int{4}
}
func (m *UpdateBlogReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBlogReq.Unmarshal(m, b)
}
func (m *UpdateBlogReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBlogReq.Marshal(b, m, deterministic)
}
func (dst *UpdateBlogReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBlogReq.Merge(dst, src)
}
func (m *UpdateBlogReq) XXX_Size() int {
	return xxx_messageInfo_UpdateBlogReq.Size(m)
}
func (m *UpdateBlogReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBlogReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBlogReq proto.InternalMessageInfo

func (m *UpdateBlogReq) GetBlog() *Blog {
	if m != nil {
		return m.Blog
	}
	return nil
}

type UpdateBlogRes struct {
	Blog                 *Blog    `protobuf:"bytes,1,opt,name=blog,proto3" json:"blog,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateBlogRes) Reset()         { *m = UpdateBlogRes{} }
func (m *UpdateBlogRes) String() string { return proto.CompactTextString(m) }
func (*UpdateBlogRes) ProtoMessage()    {}
func (*UpdateBlogRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_blog_89641c5255cf15cd, []int{5}
}
func (m *UpdateBlogRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBlogRes.Unmarshal(m, b)
}
func (m *UpdateBlogRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBlogRes.Marshal(b, m, deterministic)
}
func (dst *UpdateBlogRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBlogRes.Merge(dst, src)
}
func (m *UpdateBlogRes) XXX_Size() int {
	return xxx_messageInfo_UpdateBlogRes.Size(m)
}
func (m *UpdateBlogRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBlogRes.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBlogRes proto.InternalMessageInfo

func (m *UpdateBlogRes) GetBlog() *Blog {
	if m != nil {
		return m.Blog
	}
	return nil
}

type ReadBlogReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadBlogReq) Reset()         { *m = ReadBlogReq{} }
func (m *ReadBlogReq) String() string { return proto.CompactTextString(m) }
func (*ReadBlogReq) ProtoMessage()    {}
func (*ReadBlogReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_blog_89641c5255cf15cd, []int{6}
}
func (m *ReadBlogReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadBlogReq.Unmarshal(m, b)
}
func (m *ReadBlogReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadBlogReq.Marshal(b, m, deterministic)
}
func (dst *ReadBlogReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadBlogReq.Merge(dst, src)
}
func (m *ReadBlogReq) XXX_Size() int {
	return xxx_messageInfo_ReadBlogReq.Size(m)
}
func (m *ReadBlogReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadBlogReq.DiscardUnknown(m)
}

var xxx_messageInfo_ReadBlogReq proto.InternalMessageInfo

func (m *ReadBlogReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadBlogRes struct {
	Blog                 *Blog    `protobuf:"bytes,1,opt,name=blog,proto3" json:"blog,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadBlogRes) Reset()         { *m = ReadBlogRes{} }
func (m *ReadBlogRes) String() string { return proto.CompactTextString(m) }
func (*ReadBlogRes) ProtoMessage()    {}
func (*ReadBlogRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_blog_89641c5255cf15cd, []int{7}
}
func (m *ReadBlogRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadBlogRes.Unmarshal(m, b)
}
func (m *ReadBlogRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadBlogRes.Marshal(b, m, deterministic)
}
func (dst *ReadBlogRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadBlogRes.Merge(dst, src)
}
func (m *ReadBlogRes) XXX_Size() int {
	return xxx_messageInfo_ReadBlogRes.Size(m)
}
func (m *ReadBlogRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadBlogRes.DiscardUnknown(m)
}

var xxx_messageInfo_ReadBlogRes proto.InternalMessageInfo

func (m *ReadBlogRes) GetBlog() *Blog {
	if m != nil {
		return m.Blog
	}
	return nil
}

type DeleteBlogReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBlogReq) Reset()         { *m = DeleteBlogReq{} }
func (m *DeleteBlogReq) String() string { return proto.CompactTextString(m) }
func (*DeleteBlogReq) ProtoMessage()    {}
func (*DeleteBlogReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_blog_89641c5255cf15cd, []int{8}
}
func (m *DeleteBlogReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBlogReq.Unmarshal(m, b)
}
func (m *DeleteBlogReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBlogReq.Marshal(b, m, deterministic)
}
func (dst *DeleteBlogReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBlogReq.Merge(dst, src)
}
func (m *DeleteBlogReq) XXX_Size() int {
	return xxx_messageInfo_DeleteBlogReq.Size(m)
}
func (m *DeleteBlogReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBlogReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBlogReq proto.InternalMessageInfo

func (m *DeleteBlogReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteBlogRes struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBlogRes) Reset()         { *m = DeleteBlogRes{} }
func (m *DeleteBlogRes) String() string { return proto.CompactTextString(m) }
func (*DeleteBlogRes) ProtoMessage()    {}
func (*DeleteBlogRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_blog_89641c5255cf15cd, []int{9}
}
func (m *DeleteBlogRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBlogRes.Unmarshal(m, b)
}
func (m *DeleteBlogRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBlogRes.Marshal(b, m, deterministic)
}
func (dst *DeleteBlogRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBlogRes.Merge(dst, src)
}
func (m *DeleteBlogRes) XXX_Size() int {
	return xxx_messageInfo_DeleteBlogRes.Size(m)
}
func (m *DeleteBlogRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBlogRes.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBlogRes proto.InternalMessageInfo

func (m *DeleteBlogRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type ListBlogReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBlogReq) Reset()         { *m = ListBlogReq{} }
func (m *ListBlogReq) String() string { return proto.CompactTextString(m) }
func (*ListBlogReq) ProtoMessage()    {}
func (*ListBlogReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_blog_89641c5255cf15cd, []int{10}
}
func (m *ListBlogReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBlogReq.Unmarshal(m, b)
}
func (m *ListBlogReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBlogReq.Marshal(b, m, deterministic)
}
func (dst *ListBlogReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBlogReq.Merge(dst, src)
}
func (m *ListBlogReq) XXX_Size() int {
	return xxx_messageInfo_ListBlogReq.Size(m)
}
func (m *ListBlogReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBlogReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListBlogReq proto.InternalMessageInfo

type ListBlogRes struct {
	Blog                 *Blog    `protobuf:"bytes,1,opt,name=blog,proto3" json:"blog,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBlogRes) Reset()         { *m = ListBlogRes{} }
func (m *ListBlogRes) String() string { return proto.CompactTextString(m) }
func (*ListBlogRes) ProtoMessage()    {}
func (*ListBlogRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_blog_89641c5255cf15cd, []int{11}
}
func (m *ListBlogRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBlogRes.Unmarshal(m, b)
}
func (m *ListBlogRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBlogRes.Marshal(b, m, deterministic)
}
func (dst *ListBlogRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBlogRes.Merge(dst, src)
}
func (m *ListBlogRes) XXX_Size() int {
	return xxx_messageInfo_ListBlogRes.Size(m)
}
func (m *ListBlogRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBlogRes.DiscardUnknown(m)
}

var xxx_messageInfo_ListBlogRes proto.InternalMessageInfo

func (m *ListBlogRes) GetBlog() *Blog {
	if m != nil {
		return m.Blog
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "blog.Empty")
	proto.RegisterType((*Blog)(nil), "blog.Blog")
	proto.RegisterType((*CreateBlogReq)(nil), "blog.CreateBlogReq")
	proto.RegisterType((*CreateBlogRes)(nil), "blog.CreateBlogRes")
	proto.RegisterType((*UpdateBlogReq)(nil), "blog.UpdateBlogReq")
	proto.RegisterType((*UpdateBlogRes)(nil), "blog.UpdateBlogRes")
	proto.RegisterType((*ReadBlogReq)(nil), "blog.ReadBlogReq")
	proto.RegisterType((*ReadBlogRes)(nil), "blog.ReadBlogRes")
	proto.RegisterType((*DeleteBlogReq)(nil), "blog.DeleteBlogReq")
	proto.RegisterType((*DeleteBlogRes)(nil), "blog.DeleteBlogRes")
	proto.RegisterType((*ListBlogReq)(nil), "blog.ListBlogReq")
	proto.RegisterType((*ListBlogRes)(nil), "blog.ListBlogRes")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EmptyServiceClient is the client API for EmptyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EmptyServiceClient interface {
	DoNothing(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type emptyServiceClient struct {
	cc *grpc.ClientConn
}

func NewEmptyServiceClient(cc *grpc.ClientConn) EmptyServiceClient {
	return &emptyServiceClient{cc}
}

func (c *emptyServiceClient) DoNothing(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/blog.EmptyService/DoNothing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmptyServiceServer is the server API for EmptyService service.
type EmptyServiceServer interface {
	DoNothing(context.Context, *Empty) (*Empty, error)
}

func RegisterEmptyServiceServer(s *grpc.Server, srv EmptyServiceServer) {
	s.RegisterService(&_EmptyService_serviceDesc, srv)
}

func _EmptyService_DoNothing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmptyServiceServer).DoNothing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blog.EmptyService/DoNothing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmptyServiceServer).DoNothing(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _EmptyService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "blog.EmptyService",
	HandlerType: (*EmptyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DoNothing",
			Handler:    _EmptyService_DoNothing_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "blog.proto",
}

// BlogServiceClient is the client API for BlogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BlogServiceClient interface {
	CreateBlog(ctx context.Context, in *CreateBlogReq, opts ...grpc.CallOption) (*CreateBlogRes, error)
	ReadBlog(ctx context.Context, in *ReadBlogReq, opts ...grpc.CallOption) (*ReadBlogRes, error)
	UpdateBlog(ctx context.Context, in *UpdateBlogReq, opts ...grpc.CallOption) (*UpdateBlogRes, error)
	DeleteBlog(ctx context.Context, in *DeleteBlogReq, opts ...grpc.CallOption) (*DeleteBlogRes, error)
	ListBlogs(ctx context.Context, in *ListBlogReq, opts ...grpc.CallOption) (BlogService_ListBlogsClient, error)
}

type blogServiceClient struct {
	cc *grpc.ClientConn
}

func NewBlogServiceClient(cc *grpc.ClientConn) BlogServiceClient {
	return &blogServiceClient{cc}
}

func (c *blogServiceClient) CreateBlog(ctx context.Context, in *CreateBlogReq, opts ...grpc.CallOption) (*CreateBlogRes, error) {
	out := new(CreateBlogRes)
	err := c.cc.Invoke(ctx, "/blog.BlogService/CreateBlog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogServiceClient) ReadBlog(ctx context.Context, in *ReadBlogReq, opts ...grpc.CallOption) (*ReadBlogRes, error) {
	out := new(ReadBlogRes)
	err := c.cc.Invoke(ctx, "/blog.BlogService/ReadBlog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogServiceClient) UpdateBlog(ctx context.Context, in *UpdateBlogReq, opts ...grpc.CallOption) (*UpdateBlogRes, error) {
	out := new(UpdateBlogRes)
	err := c.cc.Invoke(ctx, "/blog.BlogService/UpdateBlog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogServiceClient) DeleteBlog(ctx context.Context, in *DeleteBlogReq, opts ...grpc.CallOption) (*DeleteBlogRes, error) {
	out := new(DeleteBlogRes)
	err := c.cc.Invoke(ctx, "/blog.BlogService/DeleteBlog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogServiceClient) ListBlogs(ctx context.Context, in *ListBlogReq, opts ...grpc.CallOption) (BlogService_ListBlogsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_BlogService_serviceDesc.Streams[0], "/blog.BlogService/ListBlogs", opts...)
	if err != nil {
		return nil, err
	}
	x := &blogServiceListBlogsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BlogService_ListBlogsClient interface {
	Recv() (*ListBlogRes, error)
	grpc.ClientStream
}

type blogServiceListBlogsClient struct {
	grpc.ClientStream
}

func (x *blogServiceListBlogsClient) Recv() (*ListBlogRes, error) {
	m := new(ListBlogRes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BlogServiceServer is the server API for BlogService service.
type BlogServiceServer interface {
	CreateBlog(context.Context, *CreateBlogReq) (*CreateBlogRes, error)
	ReadBlog(context.Context, *ReadBlogReq) (*ReadBlogRes, error)
	UpdateBlog(context.Context, *UpdateBlogReq) (*UpdateBlogRes, error)
	DeleteBlog(context.Context, *DeleteBlogReq) (*DeleteBlogRes, error)
	ListBlogs(*ListBlogReq, BlogService_ListBlogsServer) error
}

func RegisterBlogServiceServer(s *grpc.Server, srv BlogServiceServer) {
	s.RegisterService(&_BlogService_serviceDesc, srv)
}

func _BlogService_CreateBlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBlogReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServiceServer).CreateBlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blog.BlogService/CreateBlog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServiceServer).CreateBlog(ctx, req.(*CreateBlogReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogService_ReadBlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadBlogReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServiceServer).ReadBlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blog.BlogService/ReadBlog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServiceServer).ReadBlog(ctx, req.(*ReadBlogReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogService_UpdateBlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBlogReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServiceServer).UpdateBlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blog.BlogService/UpdateBlog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServiceServer).UpdateBlog(ctx, req.(*UpdateBlogReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogService_DeleteBlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBlogReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServiceServer).DeleteBlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blog.BlogService/DeleteBlog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServiceServer).DeleteBlog(ctx, req.(*DeleteBlogReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogService_ListBlogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListBlogReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BlogServiceServer).ListBlogs(m, &blogServiceListBlogsServer{stream})
}

type BlogService_ListBlogsServer interface {
	Send(*ListBlogRes) error
	grpc.ServerStream
}

type blogServiceListBlogsServer struct {
	grpc.ServerStream
}

func (x *blogServiceListBlogsServer) Send(m *ListBlogRes) error {
	return x.ServerStream.SendMsg(m)
}

var _BlogService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "blog.BlogService",
	HandlerType: (*BlogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBlog",
			Handler:    _BlogService_CreateBlog_Handler,
		},
		{
			MethodName: "ReadBlog",
			Handler:    _BlogService_ReadBlog_Handler,
		},
		{
			MethodName: "UpdateBlog",
			Handler:    _BlogService_UpdateBlog_Handler,
		},
		{
			MethodName: "DeleteBlog",
			Handler:    _BlogService_DeleteBlog_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListBlogs",
			Handler:       _BlogService_ListBlogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "blog.proto",
}

func init() { proto.RegisterFile("blog.proto", fileDescriptor_blog_89641c5255cf15cd) }

var fileDescriptor_blog_89641c5255cf15cd = []byte{
	// 357 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0xa5, 0xb1, 0x1f, 0xc9, 0xc4, 0x0a, 0x8e, 0x1e, 0x42, 0xc4, 0x0f, 0x02, 0x82, 0x1e, 0xac,
	0xa5, 0x45, 0x7f, 0x40, 0xad, 0x07, 0x41, 0x3c, 0x44, 0xbc, 0x78, 0x91, 0x36, 0x59, 0xd2, 0x85,
	0xd8, 0x8d, 0xd9, 0xad, 0xe0, 0x7f, 0xf1, 0xc7, 0xca, 0x4e, 0x5c, 0x92, 0xb4, 0x85, 0xe8, 0xad,
	0xf3, 0xf6, 0xbd, 0x79, 0x8f, 0x37, 0x0d, 0xc0, 0x3c, 0x15, 0xc9, 0x20, 0xcb, 0x85, 0x12, 0xd8,
	0xd6, 0xbf, 0x83, 0x1e, 0x74, 0xee, 0xdf, 0x33, 0xf5, 0x15, 0x44, 0xd0, 0x9e, 0xa4, 0x22, 0xc1,
	0x3d, 0xb0, 0x78, 0xec, 0xb5, 0xce, 0x5a, 0x17, 0x4e, 0x68, 0xf1, 0x18, 0x8f, 0xc0, 0x99, 0xad,
	0xd4, 0x42, 0xe4, 0x6f, 0x3c, 0xf6, 0x2c, 0x82, 0xed, 0x02, 0x78, 0x88, 0xf1, 0x10, 0x3a, 0x8a,
	0xab, 0x94, 0x79, 0x3b, 0xf4, 0x50, 0x0c, 0xe8, 0x41, 0x2f, 0x12, 0x4b, 0xc5, 0x96, 0xca, 0x6b,
	0x13, 0x6e, 0xc6, 0xe0, 0x1a, 0xfa, 0x77, 0x39, 0x9b, 0x29, 0xa6, 0xad, 0x42, 0xf6, 0x81, 0x27,
	0x40, 0x31, 0xc8, 0xcf, 0x1d, 0xc1, 0x80, 0xf2, 0xd1, 0x63, 0x11, 0x6f, 0x4d, 0x20, 0xff, 0x22,
	0x78, 0xc9, 0xe2, 0xff, 0x39, 0x54, 0x05, 0xcd, 0x0e, 0xc7, 0xe0, 0x86, 0x6c, 0x16, 0x9b, 0xfd,
	0x6b, 0x7d, 0x05, 0x57, 0xd5, 0xe7, 0xe6, 0x6d, 0xa7, 0xd0, 0x9f, 0xb2, 0x94, 0x95, 0x79, 0xd7,
	0xf7, 0x5d, 0xd6, 0x09, 0x52, 0xb7, 0x2b, 0x57, 0x51, 0xc4, 0xa4, 0x24, 0x96, 0x1d, 0x9a, 0x31,
	0xe8, 0x83, 0xfb, 0xc8, 0xa5, 0xfa, 0xdd, 0xa4, 0x93, 0x94, 0x63, 0x63, 0x92, 0xd1, 0x0d, 0xec,
	0xd2, 0x3f, 0xe1, 0x99, 0xe5, 0x9f, 0x3c, 0x62, 0x78, 0x0e, 0xce, 0x54, 0x3c, 0x09, 0xb5, 0xe0,
	0xcb, 0x04, 0xdd, 0x82, 0x4e, 0x04, 0xbf, 0x3a, 0x8c, 0xbe, 0x2d, 0x70, 0xf5, 0x16, 0x23, 0xbb,
	0x05, 0x28, 0x2f, 0x86, 0x07, 0x05, 0xb5, 0x76, 0x74, 0x7f, 0x0b, 0x28, 0x71, 0x08, 0xb6, 0xe9,
	0x0d, 0xf7, 0x0b, 0x42, 0xa5, 0x66, 0x7f, 0x03, 0x92, 0xda, 0xa9, 0xbc, 0x9c, 0x71, 0xaa, 0x1d,
	0xdf, 0xdf, 0x02, 0x92, 0xae, 0x6c, 0xd4, 0xe8, 0x6a, 0x47, 0xf0, 0xb7, 0x80, 0x12, 0xc7, 0xe0,
	0x98, 0x3e, 0xa5, 0x89, 0x58, 0xe9, 0xdb, 0xdf, 0x80, 0xe4, 0xb0, 0x35, 0xb1, 0x5f, 0xbb, 0x1a,
	0xcd, 0x92, 0x79, 0x97, 0x3e, 0xbb, 0xf1, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xaf, 0x49, 0x73,
	0x46, 0x84, 0x03, 0x00, 0x00,
}
