---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  labels:
    name: busybox
spec:
  replicas: 1
  selector: 
    matchLabels:
      name: busybox 
  template: 
    metadata:
      labels: 
        name: busybox
    spec:
      securityContext:
        fsGroup: 999
      containers:
      - name: busybox
        image: busybox
        command:
          - sleep
          - "36000"
        volumeMounts:
          - mountPath: /data
            name: demo-vol1
      volumes:
        - name: demo-vol1
          persistentVolumeClaim:
            claimName: demo-vol1-claim
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: demo-vol1-claim
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G