---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox1
  labels:
    name: busybox1
spec:
  replicas: 1
  selector: 
    matchLabels:
      name: busybox1
  template: 
    metadata:
      labels: 
        name: busybox1
    spec:
      securityContext:
        fsGroup: 999
      containers:
      - name: busybox
        image: busybox
        command:
          - sleep
          - "36000"
        volumeMounts:
          - mountPath: /data
            name: demo-vol2
      nodeSelector:
        kubernetes.io/hostname: ubuntu
      volumes:
        - name: demo-vol2
          persistentVolumeClaim:
            claimName: demo-vol2-claim
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: demo-vol2-claim
spec:
  storageClassName: openebs-device
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G