apiVersion: apps/v1
kind: Deployment
metadata:
  name: goexamplerepo
  labels:
    app: goexamplerepo
spec:
  replicas: 1
  minReadySeconds: 5
  strategy:
  # indicate which strategy we want for rolling update
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: goexamplerepo
  template:
    metadata:
      labels:
        app: goexamplerepo
    spec:
      containers:
        - name: goexamplerepo
          image: uid09552/goexamplerepo:latest
          ports:
          - containerPort: 8085
          env:
            - name: GO_EXAMPLE_SERVICE
              valueFrom:
                configMapKeyRef:
                  key: GO_EXAMPLE_SERVICE
                  name: goexamplerepo-cfg
                  optional: false
