apiVersion: v1
kind: Service
metadata:
  name: goexamplereposervice
  labels:
    app: goexamplerepo
spec:
  type: NodePort
  ports:
  - port: 8085
    targetPort: 8085
    protocol: TCP
    nodePort: 31006
    name: http
  selector:
    app: goexamplerepo